services:
  - type: web
    name: doyo-olimpo
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /api/reservas
    envVars:
      - key: NODE_ENV
        value: production
      - key: WHATSAPP_OWNER
        sync: false